build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.2

      services:
        rabbitmq: 3-management

      dependencies:
        before:
          - pecl install amqp
        after:
          - composer require --dev gos/react-amqp:^0.3

      cache:
        disabled: false
        directories:
          - ~/.composer/cache

      project_setup:
        override: true

      tests:
        override:
          - php-scrutinizer-run

before_commands:
  - "composer install --no-dev --prefer-source -a"

tools:
  external_code_coverage:
    timeout: 3000
    runs: 4
